services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
      - action: sync+restart
        path: ./src
        target: /app/src
      - action: rebuild
        path: ./pom.xml
    ports:
      - "8080:8080"
    command: mvn spring-boot:run 

